// Generated by tools/generate_stream_contracts.py. Do not edit manually.
namespace GazeLSL
{
    internal static class GazeStreamContract
    {
        public const int ChannelCount = 21;
        public static readonly string[] Labels =
        {
            "CombinedOriginX",
            "CombinedOriginY",
            "CombinedOriginZ",
            "CombinedDirectionX",
            "CombinedDirectionY",
            "CombinedDirectionZ",
            "CombinedValid",
            "LeftEyeOriginX",
            "LeftEyeOriginY",
            "LeftEyeOriginZ",
            "LeftEyeDirectionX",
            "LeftEyeDirectionY",
            "LeftEyeDirectionZ",
            "LeftEyeValid",
            "RightEyeOriginX",
            "RightEyeOriginY",
            "RightEyeOriginZ",
            "RightEyeDirectionX",
            "RightEyeDirectionY",
            "RightEyeDirectionZ",
            "RightEyeValid"
        };
        public static readonly string[] Units =
        {
            "meters",
            "meters",
            "meters",
            "normalized",
            "normalized",
            "normalized",
            "bool",
            "meters",
            "meters",
            "meters",
            "normalized",
            "normalized",
            "normalized",
            "bool",
            "meters",
            "meters",
            "meters",
            "normalized",
            "normalized",
            "normalized",
            "bool"
        };
    }
}
