// Generated by tools/generate_stream_contracts.py. Do not edit manually.
namespace GazeLSL
{
    internal static class ModelTargetStreamContract
    {
        public const string StreamName = "HoloLensModelTargetPose";
        public const string StreamType = "Calibration";
        public const string SourceId = "hololens2_stair_model_target";
        public const double NominalSrate = 0.0;
        public const string ChannelFormat = "double64";
        public const int ChannelCount = 8;
        public static readonly string[] Labels =
        {
            "PositionX",
            "PositionY",
            "PositionZ",
            "RotationX",
            "RotationY",
            "RotationZ",
            "RotationW",
            "Tracked"
        };
        public static readonly string[] Units =
        {
            "meters",
            "meters",
            "meters",
            "normalized",
            "normalized",
            "normalized",
            "normalized",
            "bool"
        };
    }
}
