// Generated by tools/generate_stream_contracts.py. Do not edit manually.
#pragma once

#include <array>
#include <cstddef>
#include <string_view>

namespace vicon_lsl {

struct HoloLensGazeChannel {
    std::string_view label;
    std::string_view unit;
};

inline constexpr std::string_view kHoloLensGazeStreamName = "HoloLensGaze";
inline constexpr std::string_view kHoloLensGazeStreamType = "Gaze";
inline constexpr std::string_view kHoloLensGazeSourceId = "hololens2_gaze";
inline constexpr double kHoloLensGazeNominalSrate = 90.0;
inline constexpr std::string_view kHoloLensGazeChannelFormat = "double64";
inline constexpr std::size_t kHoloLensGazeChannelCount = 21;

const std::array<HoloLensGazeChannel, kHoloLensGazeChannelCount>&
holoLensGazeChannels();

} // namespace vicon_lsl
