// Generated by tools/generate_stream_contracts.py. Do not edit manually.
#include "HoloLensModelTargetSchema.h"

namespace vicon_lsl {
namespace {

constexpr std::array<HoloLensModelTargetChannel, kHoloLensModelTargetChannelCount> kChannels{{
    {"PositionX", "meters"},
    {"PositionY", "meters"},
    {"PositionZ", "meters"},
    {"RotationX", "normalized"},
    {"RotationY", "normalized"},
    {"RotationZ", "normalized"},
    {"RotationW", "normalized"},
    {"Tracked", "bool"},
}};

} // namespace

const std::array<HoloLensModelTargetChannel, kHoloLensModelTargetChannelCount>&
holoLensModelTargetChannels() {
    return kChannels;
}

} // namespace vicon_lsl
