// Generated by tools/generate_stream_contracts.py. Do not edit manually.
#pragma once

#include <array>
#include <cstddef>
#include <string_view>

namespace vicon_lsl {

struct HoloLensModelTargetChannel {
    std::string_view label;
    std::string_view unit;
};

inline constexpr std::string_view kHoloLensModelTargetStreamName = "HoloLensModelTargetPose";
inline constexpr std::string_view kHoloLensModelTargetStreamType = "Calibration";
inline constexpr std::string_view kHoloLensModelTargetSourceId = "hololens2_stair_model_target";
inline constexpr double kHoloLensModelTargetNominalSrate = 0.0;
inline constexpr std::string_view kHoloLensModelTargetChannelFormat = "double64";
inline constexpr std::size_t kHoloLensModelTargetChannelCount = 8;

const std::array<HoloLensModelTargetChannel, kHoloLensModelTargetChannelCount>&
holoLensModelTargetChannels();

} // namespace vicon_lsl
