// Generated by tools/generate_stream_contracts.py. Do not edit manually.
#pragma once

namespace vicon_lsl::stream_defaults {

inline constexpr char ViconMarkers[] = "ViconMarkers";
inline constexpr char ViconSegments[] = "ViconSegments";
inline constexpr char HoloLensGaze[] = "HoloLensGaze";
inline constexpr char HoloLensModelTargetPose[] = "HoloLensModelTargetPose";

} // namespace vicon_lsl::stream_defaults
