#!/usr/bin/env python3
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "stream-contracts" / "hololens-gaze.json"
CPP_HEADER = ROOT / "vicon-lsl-bridge" / "src" / "HoloLensGazeSchema.h"
CPP_SOURCE = ROOT / "vicon-lsl-bridge" / "src" / "HoloLensGazeSchema.cpp"
CS_SOURCE = ROOT / "hololens-gaze-lsl" / "Assets" / "Scripts" / "GazeStreamContract.cs"


def render():
    contract = json.loads(MANIFEST.read_text(encoding="utf-8"))
    channels = contract["channels"]
    count = len(channels)
    header = f'''#pragma once

#include <array>
#include <cstddef>
#include <string_view>

namespace vicon_lsl {{

struct HoloLensGazeChannel {{
    std::string_view label;
    std::string_view unit;
}};

inline constexpr std::size_t kHoloLensGazeChannelCount = {count};
const std::array<HoloLensGazeChannel, kHoloLensGazeChannelCount>&
holoLensGazeChannels();

}} // namespace vicon_lsl
'''
    rows = "\n".join(f'    {{"{c["label"]}", "{c["unit"]}"}},' for c in channels)
    source = f'''#include "HoloLensGazeSchema.h"

namespace vicon_lsl {{
namespace {{

constexpr std::array<HoloLensGazeChannel, kHoloLensGazeChannelCount> kChannels{{{{
{rows}
}}}};

}} // namespace

const std::array<HoloLensGazeChannel, kHoloLensGazeChannelCount>&
holoLensGazeChannels() {{
    return kChannels;
}}

}} // namespace vicon_lsl
'''
    labels = ",\n".join(f'            "{c["label"]}"' for c in channels)
    units = ",\n".join(f'            "{c["unit"]}"' for c in channels)
    csharp = f'''// Generated by tools/generate_stream_contracts.py. Do not edit manually.
namespace GazeLSL
{{
    internal static class GazeStreamContract
    {{
        public const int ChannelCount = {count};
        public static readonly string[] Labels =
        {{
{labels}
        }};
        public static readonly string[] Units =
        {{
{units}
        }};
    }}
}}
'''
    return {CPP_HEADER: header, CPP_SOURCE: source, CS_SOURCE: csharp}


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    stale = []
    for path, content in render().items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                stale.append(path.relative_to(ROOT))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8", newline="\n")
    if stale:
        raise SystemExit("Generated stream contracts are stale: " + ", ".join(map(str, stale)))


if __name__ == "__main__":
    main()
