#!/usr/bin/env python3
"""Generate the native and managed HoloLens stream-contract facades."""

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CONTRACT_ROOT = ROOT / "stream-contracts"
GAZE_MANIFEST = CONTRACT_ROOT / "hololens-gaze.json"
MODEL_TARGET_MANIFEST = CONTRACT_ROOT / "hololens-model-target.json"

CPP_GAZE_HEADER = ROOT / "vicon-lsl-bridge" / "src" / "HoloLensGazeSchema.h"
CPP_GAZE_SOURCE = ROOT / "vicon-lsl-bridge" / "src" / "HoloLensGazeSchema.cpp"
CPP_TARGET_HEADER = ROOT / "vicon-lsl-bridge" / "src" / "HoloLensModelTargetSchema.h"
CPP_TARGET_SOURCE = ROOT / "vicon-lsl-bridge" / "src" / "HoloLensModelTargetSchema.cpp"
CPP_STREAM_DEFAULTS = ROOT / "vicon-lsl-bridge" / "src" / "StreamDefaults.generated.h"
CS_GAZE_SOURCE = (
    ROOT / "hololens-gaze-lsl" / "Assets" / "Scripts" / "GazeStreamContract.cs"
)
CS_TARGET_SOURCE = (
    ROOT
    / "hololens-gaze-lsl"
    / "Assets"
    / "Scripts"
    / "ModelTargetStreamContract.cs"
)

REQUIRED_FIELDS = (
    "contract_id",
    "name",
    "type",
    "source_id",
    "nominal_srate",
    "channel_format",
    "channels",
)


def quoted(value):
    return json.dumps(value, ensure_ascii=True)


def number_literal(value):
    value = float(value)
    return f"{value:.1f}" if value.is_integer() else repr(value)


def load_contract(path):
    contract = json.loads(path.read_text(encoding="utf-8"))
    missing = [field for field in REQUIRED_FIELDS if field not in contract]
    if missing:
        raise ValueError(f"{path.name} is missing fields: {', '.join(missing)}")
    if not isinstance(contract["channels"], list) or not contract["channels"]:
        raise ValueError(f"{path.name} must contain at least one channel")
    labels = []
    for index, channel in enumerate(contract["channels"]):
        if not isinstance(channel, dict) or not channel.get("label") or not channel.get("unit"):
            raise ValueError(f"{path.name} channel {index} needs label and unit")
        labels.append(channel["label"])
    if len(labels) != len(set(labels)):
        raise ValueError(f"{path.name} contains duplicate channel labels")
    if contract["channel_format"] != "double64":
        raise ValueError(f"{path.name} uses unsupported channel_format")
    return contract


def render_cpp_schema(contract, schema_name, channel_name, function_name):
    channels = contract["channels"]
    count = len(channels)
    if not schema_name.endswith("Schema"):
        raise ValueError(f"{schema_name} must end with Schema")
    prefix = schema_name[: -len("Schema")]
    header = f'''// Generated by tools/generate_stream_contracts.py. Do not edit manually.
#pragma once

#include <array>
#include <cstddef>
#include <string_view>

namespace vicon_lsl {{

struct {channel_name} {{
    std::string_view label;
    std::string_view unit;
}};

inline constexpr std::string_view k{prefix}StreamName = {quoted(contract["name"])};
inline constexpr std::string_view k{prefix}StreamType = {quoted(contract["type"])};
inline constexpr std::string_view k{prefix}SourceId = {quoted(contract["source_id"])};
inline constexpr double k{prefix}NominalSrate = {number_literal(contract["nominal_srate"])};
inline constexpr std::string_view k{prefix}ChannelFormat = {quoted(contract["channel_format"])};
inline constexpr std::size_t k{prefix}ChannelCount = {count};

const std::array<{channel_name}, k{prefix}ChannelCount>&
{function_name}();

}} // namespace vicon_lsl
'''
    rows = "\n".join(
        f'    {{{quoted(channel["label"])}, {quoted(channel["unit"])}}},'
        for channel in channels
    )
    source = f'''// Generated by tools/generate_stream_contracts.py. Do not edit manually.
#include "{schema_name}.h"

namespace vicon_lsl {{
namespace {{

constexpr std::array<{channel_name}, k{prefix}ChannelCount> kChannels{{{{
{rows}
}}}};

}} // namespace

const std::array<{channel_name}, k{prefix}ChannelCount>&
{function_name}() {{
    return kChannels;
}}

}} // namespace vicon_lsl
'''
    return header, source


def render_csharp_metadata(contract, class_name, write_gaze_sample=False):
    channels = contract["channels"]
    labels = ",\n".join(f"            {quoted(c['label'])}" for c in channels)
    units = ",\n".join(f"            {quoted(c['unit'])}" for c in channels)
    sample_method = ""
    if write_gaze_sample:
        writes = "\n".join(
            f"            sample[{index}] = frame.{channel['label']}"
            + (" ? 1.0 : 0.0;" if channel["unit"] == "bool" else ";")
            for index, channel in enumerate(channels)
        )
        sample_method = f'''

        public static void WriteSample(GazeSample frame, double[] sample)
        {{
            if (sample == null)
            {{
                throw new System.ArgumentNullException(nameof(sample));
            }}

            if (sample.Length < ChannelCount)
            {{
                throw new System.ArgumentException(
                    "The gaze sample buffer must contain at least " + ChannelCount + " elements.",
                    nameof(sample));
            }}

{writes}
        }}'''

    return f'''// Generated by tools/generate_stream_contracts.py. Do not edit manually.
namespace GazeLSL
{{
    internal static class {class_name}
    {{
        public const string StreamName = {quoted(contract["name"])};
        public const string StreamType = {quoted(contract["type"])};
        public const string SourceId = {quoted(contract["source_id"])};
        public const double NominalSrate = {number_literal(contract["nominal_srate"])};
        public const string ChannelFormat = {quoted(contract["channel_format"])};
        public const int ChannelCount = {len(channels)};
        public static readonly string[] Labels =
        {{
{labels}
        }};
        public static readonly string[] Units =
        {{
{units}
        }};{sample_method}
    }}
}}
'''


def render_stream_defaults(gaze, target):
    return f'''// Generated by tools/generate_stream_contracts.py. Do not edit manually.
#pragma once

namespace vicon_lsl::stream_defaults {{

inline constexpr char ViconMarkers[] = "ViconMarkers";
inline constexpr char ViconSegments[] = "ViconSegments";
inline constexpr char HoloLensGaze[] = {quoted(gaze["name"])};
inline constexpr char HoloLensModelTargetPose[] = {quoted(target["name"])};

}} // namespace vicon_lsl::stream_defaults
'''


def render():
    gaze = load_contract(GAZE_MANIFEST)
    target = load_contract(MODEL_TARGET_MANIFEST)
    if gaze["contract_id"] == target["contract_id"]:
        raise ValueError("stream contract ids must be unique")

    gaze_header, gaze_source = render_cpp_schema(
        gaze,
        "HoloLensGazeSchema",
        "HoloLensGazeChannel",
        "holoLensGazeChannels",
    )
    target_header, target_source = render_cpp_schema(
        target,
        "HoloLensModelTargetSchema",
        "HoloLensModelTargetChannel",
        "holoLensModelTargetChannels",
    )
    return {
        CPP_GAZE_HEADER: gaze_header,
        CPP_GAZE_SOURCE: gaze_source,
        CPP_TARGET_HEADER: target_header,
        CPP_TARGET_SOURCE: target_source,
        CPP_STREAM_DEFAULTS: render_stream_defaults(gaze, target),
        CS_GAZE_SOURCE: render_csharp_metadata(gaze, "GazeStreamContract", True),
        CS_TARGET_SOURCE: render_csharp_metadata(
            target, "ModelTargetStreamContract", False
        ),
    }


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when a generated file differs from its manifest",
    )
    args = parser.parse_args()
    stale = []
    for path, content in render().items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                stale.append(path.relative_to(ROOT))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8", newline="\n")
    if stale:
        raise SystemExit(
            "Generated stream contracts are stale: " + ", ".join(map(str, stale))
        )


if __name__ == "__main__":
    main()
